# Based image
FROM node:20-alpine

# Set working dir
WORKDIR /restaurant-server

# Copy package*.json file first
COPY ./package.json  ./

# copy the rest of application
COPY ./src .env ./env/.env.production ./

# install pakages
RUN npm install

# Expose the port your server will listen on
EXPOSE 7071

# command to start our application
CMD [ "npm" , "run" , "dev" ]