# version: '3.8'
services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
      - KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE=true

  #Databases
  postgresql-db:
   container_name: postgresql-db
   build: ../backend/services/restaurant-service/database 
   volumes:
    - postgres_data:/var/lib/postgresql/data
   ports:
    - "5432:5432"
   env_file: 
    - ../backend/services/restaurant-service/env/.env.production
   healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 30s
    timeout: 60s
    retries: 5
  
  mongo-db:
   container_name: mongo-db
   image: mongo:latest
   ports:
      - "27017:27017"
   volumes:
      - mongo-data:/data/db 
   env_file:
    - ../backend/services/cart-service/env/.env.production
    - ../backend/services/payment-service/env/.env.production
  
  #Services
  api-gateway:
   container_name: api-gateway
   build: ../backend/services/api-gateway
   ports: 
    - 4000:4000 
   env_file:
    - ../backend/services/api-gateway/env/.env.production 

  restaurant-service:
   container_name: restaurant-service
   build: ../backend/services/restaurant-service    
   ports: 
    - 7071:7071
   env_file: 
    - ../backend/services/restaurant-service/env/.env.production   
   depends_on:
    postgresql-db: 
     condition: service_healthy

  cart-service:
   container_name: cart-service
   build: ../backend/services/cart-service
   ports: 
    - 7074:7074
   env_file:
    - ../backend/services/cart-service/env/.env.production
   depends_on: 
    - mongo-db 
  
  payment-service:
   container_name: payment-service
   build: ../backend/services/payment-service
   ports: 
    - 7072:7072 
   env_file: 
    - ../backend/services/payment-service/env/.env.production 
   depends_on: 
    - mongo-db

  order-service:
   container_name: order-service
   build: ../backend/services/order-service
   ports: 
    - 7073:7073
   env_file:
     - ../backend/services/order-service/env/.env.production
   depends_on:
    - mongo-db  
  
  # log-service:
  #  container_name: log-service
  #  build: ../backend/services/log-service
  #  ports: 
  #   - 7073:7073
  #  env_file:
  #    - ../backend/services/log-service/env/.env.production

  # email-service:
  #  container_name: email-service
  #  build: ../backend/services/email-service
  #  ports: 
  #   - 7073:7073
  #  env_file:
  #    - ../backend/services/email-service/env/.env.production
  
  web-server:
   container_name: web-server
   build: ../frontend/
   ports: 
    - 9090:9090
   depends_on:
    - api-gateway
    - restaurant-service
    - payment-service
    - cart-service

volumes:
 postgres_data:
 mongo-data:
