# Based image
FROM node:20-alpine

# Set working dir
WORKDIR /api-gateway-server

# Copy package*.json file first
COPY ./package.json  ./
COPY ./src .env ./env/.env.production ./

# install pakages
RUN npm install

# Expose the port your server will listen on
EXPOSE 4000

# command to start our application
CMD [ "node" , "index.js"]