# This configuration is for a Single Page Application (SPA)
server {
    # Cloud Run automatically sets the PORT environment variable. 
    # Nginx cannot read environment variables in the 'listen' directive directly, 
    # so we default to 8080 for simplicity and map it to $PORT later or let Cloud Run handle it.
    listen       8080;
    listen  [::]:8080;
    
    # Set the root directory for serving files
    root /usr/share/nginx/html;
    index index.html;


    # Crucial for React Router (or similar) SPAs:
    # This tries to serve the requested file, then the directory, 
    # and finally falls back to serving index.html.
    # This lets your frontend routing library handle all routes.
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        
        proxy_pass http://api-gateway:4000/api/;

        # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection 'upgrade';

        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
    }

    # You can add configuration for your backend API calls here if you want 
    # Nginx to act as a reverse proxy (NOT recommended for two separate Cloud Run services):
    # location /api/ {
    #     proxy_pass http://<YOUR_BACKEND_URL>;
    # }

    
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}